# Generated by Django 6.0.2 on 2026-02-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uplay_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='max_participants',
            field=models.PositiveIntegerField(default=16),
        ),
        migrations.AddField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('open', 'Registration Open'), ('full', 'Tournament Full'), ('ongoing', 'In Progress'), ('completed', 'Finished'), ('cancelled', 'Cancelled')], default='open', max_length=20),
        ),
    ]
