# Generated by Django 6.0.2 on 2026-02-20 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uplay_app', '0003_category_tournament_entry_fee_tournament_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='uplay_app.category'),
        ),
    ]
