# Generated by Django 6.0.2 on 2026-03-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uplay_app', '0006_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='banner_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournament_format',
            field=models.CharField(default='1v1 Bracket', max_length=100),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('open', 'Registration Open'), ('live', 'Live Now'), ('completed', 'Completed'), ('full', 'Tournament Full'), ('ongoing', 'In Progress'), ('cancelled', 'Cancelled')], default='open', max_length=20),
        ),
    ]
