# Generated by Django 6.0.2 on 2026-03-04 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uplay_app', '0008_user_avatar_name_squad_friendship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squad',
            name='avatar_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar_name',
        ),
    ]
