# Generated by Django 6.0.2 on 2026-03-09 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uplay_app', '0009_remove_squad_avatar_name_remove_user_avatar_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('psn_id', models.CharField(blank=True, max_length=100, null=True)),
                ('xbox_id', models.CharField(blank=True, max_length=100, null=True)),
                ('riot_id', models.CharField(blank=True, max_length=100, null=True)),
                ('activision_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ea_id', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('account_name', models.CharField(blank=True, max_length=150, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
